### ISSUE TITLE
Exception during reasoning output

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#147]
Running the CF checker on [this file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANFOG/delayed/catalog.html?dataset=IMOS/eMII/checker_test/ANFOG/delayed/IMOS_ANFOG_BCEOPSTUV_20140915T003743Z_SL209_FV01_timeseries_END-20141009T212310Z.nc), I get the following exception during the printing of the reasoning messages:

```
Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mhidas/bin/cchecker.py", line 36, in <module>
    sys.exit(main())
  File "/home/mhidas/bin/cchecker.py", line 27, in main
    args.format)
  File "/home/mhidas/code/compliance-checker/compliance_checker/runner.py", line 56, in run_checker
    groups = cls.stdout_output(cs, score_groups, verbose, limit)
  File "/home/mhidas/code/compliance-checker/compliance_checker/runner.py", line 91, in stdout_output
    cs.non_verbose_output_generation(score_list, groups, limit, points, out_of)
  File "/home/mhidas/code/compliance-checker/compliance_checker/suite.py", line 280, in non_verbose_output_generation
    self.reasoning_routine(groups, 0)
  File "/home/mhidas/code/compliance-checker/compliance_checker/suite.py", line 369, in reasoning_routine
    print wrapper.fill('%-39s:%1s:%6s/%2s : %s' %(str(indent*'    '+res.name)[0:39], res.weight, str(res.value[0]), str(res.value[1]), str(", ".join(res.msgs))))
TypeError: sequence item 0: expected string, tuple found
```

**Comment by daf** [comment]
@mhidas, thanks, looks like the CF fill value outside range check was from a very early implementation and had never been updated to current style.  I've got a fix in PR #147.
