### ISSUE TITLE
Add references to checker output?

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#154]
For a data provider trying to correct issues picked up by the checker, it would be helpful if the brief reasoning message for each failed test could be followed by a reference (URL or text) to the relevant section of the convention document. Could we add a `reference` attribute of the `Result` object, and list these separately in the checker output (perhaps at the end)?

**Comment by daf** [comment]
@mhidas , @lukecampbell addressed this in #167 and made the ref part of the check name itself.  If you get a minute can you please evaluate it and see if it addresses this issue well?

**Comment by mhidas** [comment]
@daf @lukecampbell Thanks. I've finally had a look at this. It's not quite what I had in mind, but it might just do the trick. However, breaking the grouping (as you pointed out https://github.com/ioos/compliance-checker/pull/167#issuecomment-144741447) is a possible drawback. I don't care about combining scores according to the grouping, but it does order the results in a meaningful way.

Having said that, I haven't actually managed to see what the new output looks like, because even though the unittests pass, whenever I try to run the cf checker on a file that doesn't pass (running code at db62cea9e3ba90843ea0961b734077628f444c70), I get
```
$ cchecker.py -t=cf compliance_checker/tests/data/bad_data_type.nc 
Running Compliance Checker on the dataset from: compliance_checker/tests/data/bad_data_type.nc
Traceback (most recent call last):
  File "/home/mhidas/bin/cchecker.py", line 47, in <module>
    sys.exit(main())
  File "/home/mhidas/bin/cchecker.py", line 36, in main
    args.format)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/runner.py", line 48, in run_checker
    score_groups = cs.run(ds, *checker_names)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 100, in run
    groups = self.scores(vals)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 490, in scores
    grouped = self._group_raw(raw_scores)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 538, in _group_raw
    grouped = itertools.groupby(sorted(raw_scores, key=group_func), key=group_func)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
```

or
```
$ cchecker.py -t=cf http://thredds.aodn.org.au/thredds/dodsC/IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-QLD_TZ_20140907T063947Z_ITFTIS_FV01_ITFTIS-1409-SBE39-94_END-20150207T065000Z_C-20150219T005030Z.nc
Running Compliance Checker on the dataset from: http://thredds.aodn.org.au/thredds/dodsC/IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-QLD_TZ_20140907T063947Z_ITFTIS_FV01_ITFTIS-1409-SBE39-94_END-20150207T065000Z_C-20150219T005030Z.nc
Traceback (most recent call last):
  File "/home/mhidas/bin/cchecker.py", line 47, in <module>
    sys.exit(main())
  File "/home/mhidas/bin/cchecker.py", line 36, in main
    args.format)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/runner.py", line 48, in run_checker
    score_groups = cs.run(ds, *checker_names)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 100, in run
    groups = self.scores(vals)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 490, in scores
    grouped = self._group_raw(raw_scores)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 546, in _group_raw
    cv = self._group_raw(map(trim_groups, v), k, level+1)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 538, in _group_raw
    grouped = itertools.groupby(sorted(raw_scores, key=group_func), key=group_func)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 532, in group_func
    return r.name[0:1][0]
IndexError: list index out of range
```

**Comment by lukecampbell** [comment]
Thanks! I'll take a look

**Comment by mhidas** [comment]
@lukecampbell I just realised I've seen the second exception (in `group_func`) before, or at least something very similar. I got as far as figuring out that it was probably due to multiple Result objects having exactly the same name.
