### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#178]
We need to fix the CF formatting. This can be produced by generating an HTML report for the bad datasets under tests.

**Comment by mhidas** [comment]
@lukecampbell I assume you're referring to the exceptions I mentioned in https://github.com/ioos/compliance-checker/issues/154#issuecomment-147624951 ?

**Comment by mhidas** [comment]
Here's another one (using code as at db62cea9e3ba90843ea0961b734077628f444c70):

```
$ cchecker.py -t=cf compliance_checker/tests/data/bad_region.nc 
Running Compliance Checker on the dataset from: compliance_checker/tests/data/bad_region.nc


--------------------------------------------------------------------------------
                     The dataset scored 39 out of 56 points                     
                              during the cf check                               
--------------------------------------------------------------------------------
                               Scoring Breakdown:                               


all_features_are_same_type              :2:     0/0
contiguous_ragged_array                 :2:     0/0
coordinates_and_metadata                :2:     0/0
feature_type                            :2:     0/0
incomplete_multidim_array               :2:     0/0
indexed_ragged_array                    :2:     0/0
missing_data                            :2:     0/0
orthogonal_multidim_array               :2:     0/0
                                 High Priority                                  
--------------------------------------------------------------------------------
    Name                            :Priority: Score
units                                   :3:     0/3
§2.2 Valid netCDF data types            :3:     7/8
§2.3 Legal variable names               :3:     8/8
§2.4 Unique dimensions                  :3:     7/8
§2.5.1 _FillValue outside of valid rang :3:     1/2
§2.6.1 Global Attribute Conventions inc :3:     0/1
§2.6.2 Convention Attributes            :3:     0/1
§3.3 Standard Names                     :3:     2/4
§4 Axis attributes and coordinate varia :3:     3/5
§4 Coordinate Variable latitude contain :3:     1/1
§4 Coordinate Variable longitude contai :3:     1/1


                                Medium Priority                                 
--------------------------------------------------------------------------------
    Name                            :Priority: Score
§4 Coordinate Variables                 :2:     3/3
§4.1 Coordinates representing latitude  :2:     1/3
§4.1 Coordinates representing longitude :2:     1/3
§4.4 Time coordinate variable and attri :3:     0/1
§5.1 Geophysical variables contain vali :2:     3/3
§6.2 Alternative Coordinates            :2:     1/1


--------------------------------------------------------------------------------
                  Reasoning for the failed tests given below:                   


Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
units                                  :3:     0/ 3 :  
    longitudeZZ                        :3:     0/ 1 :  
        present                        :3:     0/ 1 : units attribute required
    salinity                           :3:     0/ 1 :  
        known                          :3:     0/ 1 : unknown units type (Chad
                                                      Pennington)
    time                               :3:     0/ 1 :  
        present                        :3:     0/ 1 : units attribute required
Traceback (most recent call last):
  File "/home/mhidas/bin/cchecker.py", line 47, in <module>
    sys.exit(main())
  File "/home/mhidas/bin/cchecker.py", line 36, in main
    args.format)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/runner.py", line 58, in run_checker
    groups = cls.stdout_output(cs, score_groups, verbose, limit)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/runner.py", line 88, in stdout_output
    cs.non_verbose_output_generation(score_list, groups, limit, points, out_of)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 339, in non_verbose_output_generation
    self.reasoning_routine(groups, 0)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 428, in reasoning_routine
    print wrapper.fill('%-39s:%1s:%6s/%2s : %s' %(str(indent*'    '+res.name)[0:39], res.weight, str(res.value[0]), str(res.value[1]), str(", ".join(res.msgs))))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 0: ordinal not in range(128)
```

**Comment by lukecampbell** [comment]
yeah that's a unicode error, that's deserving of it's own bug.
