### ISSUE TITLE
IndexError: list index out of range in suite.py (running CF checks)

### ISSUE THREAD

**Issue by mhidas** [ioos/compliance-checker#183]
I'm still getting this error for a lot of files, e.g.
``` bash
$ cchecker.py -t=cf compliance_checker/tests/data/bad_data_type.nc 
Running Compliance Checker on the dataset from: compliance_checker/tests/data/bad_data_type.nc
Traceback (most recent call last):
  File "/home/mhidas/bin/cchecker.py", line 51, in <module>
    sys.exit(main())
  File "/home/mhidas/bin/cchecker.py", line 40, in main
    args.format)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/runner.py", line 33, in run_checker
    score_groups = cs.run(ds, *checker_names)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 116, in run
    groups = self.scores(vals)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 510, in scores
    grouped = self._group_raw(raw_scores)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 569, in _group_raw
    cv = self._group_raw(map(trim_groups, v), k, level+1)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 561, in _group_raw
    grouped = itertools.groupby(sorted(raw_scores, key=group_func), key=group_func)
  File "/home/mhidas/work/code/compliance-checker/compliance_checker/suite.py", line 552, in group_func
    retval = r.name[0:1][0]
IndexError: list index out of range
```

I think I first started seeing this issue after the new result naming scheme was introduced in #167 
As I mentioned before, I got as far as figuring out that it was probably due to multiple Result objects having exactly the same name.

**Comment by mhidas** [comment]
Ok, I think #183 does the job.
