### ISSUE TITLE
Error when upgrading compliance_checker

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#249]
I just tried to upgrade my local compliance_checker and I received an error. Below is the output fomr the Anaconda command prompt:
```
C:\Users\mbiddle\AppData\Local\Continuum\Anaconda>pip install --upgrade compliance_checker
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting compliance-checker
  Downloading compliance-checker-2.1.0.tar.gz (580kB)
    100% |################################| 581kB 327kB/s
Collecting OWSLib>=0.8.3 (from compliance-checker)
  Downloading OWSLib-0.11.0.tar.gz (113kB)
    100% |################################| 114kB 871kB/s
Collecting lxml>=3.2.1 (from compliance-checker)
  Downloading lxml-3.6.0-cp27-none-win_amd64.whl (3.3MB)
    100% |################################| 3.3MB 79kB/s
Collecting cf-units>=0.1.1 (from compliance-checker)
  Downloading cf_units-1.0.0.tar.gz (41kB)
    100% |################################| 45kB 1.3MB/s
Collecting requests>=2.2.1 (from compliance-checker)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.2 (from compliance-checker)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB)
    100% |################################| 204kB 660kB/s
Collecting Jinja2>=2.7.3 (from compliance-checker)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting setuptools>=15.0 (from compliance-checker)
  Downloading setuptools-20.7.0-py2.py3-none-any.whl (508kB)
    100% |################################| 512kB 375kB/s
Collecting pytz (from OWSLib>=0.8.3->compliance-checker)
  Downloading pytz-2016.3-py2.py3-none-any.whl (479kB)
    100% |################################| 483kB 660kB/s
Collecting pyproj (from OWSLib>=0.8.3->compliance-checker)
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\mbiddle\appdata\local\temp\2\pip-build-yo9fkd\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "C:\Users\mbiddle\AppData\Local\Continuum\Anaconda\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "C:\Users\mbiddle\AppData\Local\Continuum\Anaconda\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Users\mbiddle\AppData\Local\Continuum\Anaconda\lib\site-packages\setuptools-18.1-py2.7.egg\setuptools\msvc9_support.p
y", line 60, in query_vcvarsall
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http:/
/aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mbiddle\appdata\local\temp\2\pip-build-yo9fkd\pyproj
```
Is this something I should be concerned about?

**Comment by ocefpaf** [comment]
@mbiddle-nodc there are no `wheels` (Python binaries that are download-ready) for [`pyproj` at PyPI](https://pypi.python.org/pypi/pyproj). The devs upload only the source code. What `pip` is trying to do for you, and failing, is to compile that source.

Compiling source code on Windows is not a trivial task! I recommend you to install `compliance_checker` with conda. If you are not a conda user take a look at [these](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) instructions first. Then type:

```shell
conda install -c conda-forge compliance-checker
```

PS: That is not an issue with `compliance-checker`. If you don't want or cannot use conda you might want to request `pyproj` devs to provide binary `wheels` at PyPI.
