### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by lukecampbell** [ioos/compliance-checker#263]
Some THREDD instances are behind a reverse-proxy and do some 301 redirecting when copy-pasting the OPeNDAP URL into input for Compliance-Checker. It would be good to have CChecker recognize this and get the forwarded address. I.e. follow-redirects.

**Comment by benjwadams** [comment]
Do you happen to have any URIs I could test this against?

**Comment by lukecampbell** [comment]
http://data.ioos.us/thredds/dodsC/deployments/drudnick/sp049-20160405T1844/sp049-20160405T1844.nc3.nc

Returns a 301

**Comment by benjwadams** [comment]
Unable to reproduce with `netCDF4==1.2.4` on Python 3.4.3 and `netCDF4==1.2.1` on Python 2.7.5.

**Comment by lukecampbell** [comment]
```
(cchecker)➜  compliance-checker git:(master) compliance-checker -t cf -c strict http://data.ioos.us/thredds/dodsC/deployments/drudnick/sp049-20160405T1844/sp049-20160405T1844.nc3.nc
Could not load ncei-timeseries = cc_plugin_ncei.ncei_timeseries:NCEITimeSeries : 'module' object has no attribute 'NCEITimeSeries'
Could not load acdd:1.1 = compliance_checker.acdd:ACDD1_1Check : 'module' object has no attribute 'ACDD1_1Check'
Could not load acdd:1.3 = compliance_checker.acdd:ACDD1_3Check : 'module' object has no attribute 'ACDD1_3Check'
Could not load acdd = compliance_checker.acdd:ACDD1_1Check : 'module' object has no attribute 'ACDD1_1Check'
Running Compliance Checker on the dataset from: http://data.ioos.us/thredds/dodsC/deployments/drudnick/sp049-20160405T1844/sp049-20160405T1844.nc3.nc
Traceback (most recent call last):
  File "/Users/lcampbell/.virtualenvs/cchecker/bin/compliance-checker", line 9, in <module>
    load_entry_point('compliance-checker', 'console_scripts', 'compliance-checker')()
  File "/Users/lcampbell/Documents/Dev/code/compliance-checker/cchecker.py", line 41, in main
    args.format)
  File "/Users/lcampbell/Documents/Dev/code/compliance-checker/compliance_checker/runner.py", line 33, in run_checker
    ds = cs.load_dataset(ds_loc)
  File "/Users/lcampbell/Documents/Dev/code/compliance-checker/compliance_checker/suite.py", line 472, in load_dataset
    raise Exception("Could not understand response code %s and content-type %s" % (rhead.status_code, rhead.headers.get('content-type', 'none')))
Exception: Could not understand response code 301 and content-type text/html
```

**Comment by lukecampbell** [comment]
netcdf: 4.3.3.1_4

**Comment by benjwadams** [comment]
Hmmm, now I'm getting issues.  Doesn't look like a NetCDF issue, but maybe a requests issue instead.
