### ISSUE TITLE
CDL check fails on text files (py3)

### ISSUE THREAD

**Issue by daf** [ioos/compliance-checker#308]
The recent CDL additions (#297) have broken the ability to pass a text file on the command line (IE a getcaps/describesensor xml document) on python 3 environments:

```
~/dev/compliance-checker -> python cchecker.py --test ioos ~/Downloads/aoos_sos_getcaps.xml
Running Compliance Checker on the dataset from: /home/daf/Downloads/aoos_sos_getcaps.xml
Traceback (most recent call last):
  File "cchecker.py", line 79, in <module>
    sys.exit(main())
  File "cchecker.py", line 68, in main
    args.format)
  File "/home/daf/dev/compliance-checker/compliance_checker/runner.py", line 44, in run_checker
    ds = cs.load_dataset(ds_loc)
  File "/home/daf/dev/compliance-checker/compliance_checker/suite.py", line 576, in load_dataset
    elif is_cdl_file(ds_str, first_chunk):
  File "/home/daf/dev/compliance-checker/compliance_checker/suite.py", line 567, in is_cdl_file
    if data.startswith('netcdf') or 'dimensions' in data:
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by benjwadams** [comment]
WTB tests PST

**Comment by benjwadams** [comment]
Python string encoding funtimes.  I'll handle this and add some tests too.
