### ISSUE TITLE
The 'ioos_sos' test doesn't return any results, needs better error handling

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#536]
I have the latest Compliance Checker installed via Conda Forge.  When I try to run the 'ioos_sos' test I get an unhelpful stdout response, then and XML response parsing error message.  I've tested this with a couple different active SOS services from the IOOS Catalog.

Error:
```
$ compliance-checker -t ioos_sos -f json http://thredds.aoos.org/thredds/sos/aoos/cruises/ecofoci/4mf01.nc?service=SOS&version=1.0.0&request=GetCapabilities
[1] 911720
[2] 911740
[2]+  Done                    version=1.0.0
(IOOS)
Traceback (most recent call last):
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\Scripts\compliance-checker-script.py", line 5, in <module>
    sys.exit(cchecker.main())
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\Scripts\cchecker.py", line 73, in main
    args.format)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\lib\site-packages\compliance_checker\runner.py", line 50, in run_checker
    ds = cs.load_dataset(ds_loc)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\lib\site-packages\compliance_checker\suite.py", line 527, in load_dataset
    return self.load_remote_dataset(ds_str)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\lib\site-packages\compliance_checker\suite.py", line 543, in load_remote_dataset
    return self.process_doc(response.content)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\lib\site-packages\compliance_checker\suite.py", line 499, in process_doc
    raise ValueError("Unrecognized XML root element: %s" % xml_doc.tag)
ValueError: Unrecognized XML root element: {http://www.opengis.net/ows/1.1}ExceptionReport

[1]+  Exit 1                  compliance-checker -t ioos_sos -f json http://thredds.aoos.org/thredds/sos/aoos/cruises/ecofoci/4mf01.nc?service=SOS
```

Also, if I mistakenly feed the 'ioos_sos' test an OPeNDAP URL, the error message response isn't very useful (indicates the checker isn't installed, rather than that I gave it a URL it wasn't expecting):

```
 compliance-checker -t ioos_sos -f json http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/avg/ESPRESSO_Real-Time_v2_Averages_Best
No valid checkers found for tests 'ioos_sos'
Traceback (most recent call last):
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\Scripts\compliance-checker-script.py", line 5, in <module>
    sys.exit(cchecker.main())
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\Scripts\cchecker.py", line 73, in main
    args.format)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\miniconda3_2017\envs\IOOS\lib\site-packages\compliance_checker\runner.py", line 56, in run_checker
    raise ValueError("No checks found, please check the name of the checker(s) and that they are installed")
ValueError: No checks found, please check the name of the checker(s) and that they are installed
```

**Comment by Bobfrat** [comment]
I'll check conda in a minute (I use virtualenv + pip) but I had success by wrapping the URL in quotes. I'm showing text output here for brevity but json worked too.
```
compliance-checker -t ioos_sos "http://thredds.aoos.org/thredds/sos/aoos/cruises/ecofoci/4mf01.nc?service=SOS&version=1.0.0&request=GetCapabilities"

--------------------------------------------------------------------------------
                      The dataset scored 8 out of 8 points
                           during the ioos_sos check
--------------------------------------------------------------------------------
All tests passed!
```

I can verify the second issue here, we can create a better error message for that situation.

**Comment by ocefpaf** [comment]
Just tested it locally and it seems to be working:

```shell
$ conda create --yes -n TEST python=3.6 compliance-checker
$ source activate TEST
$ compliance-checker -t ioos_sos -f json "http://thredds.aoos.org/thredds/sos/aoos/cruises/ecofoci/4mf01.nc?service=SOS&version=1.0.0&request=GetCapabilities"
{
  "ioos_sos": {
    "scored_points": 8,
    "possible_points": 8,
    "high_count": 0,
    "medium_count": 0,
    "low_count": 0,
    "high_priorities": [],
    "medium_priorities": [
      {
        "name": "data_format_template_version",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_contact_email",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_contact_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_provider_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_title",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_type_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_type_version",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "variable_names",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      }
    ],
    "low_priorities": [],
    "all_priorities": [
      {
        "name": "data_format_template_version",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_contact_email",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_contact_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_provider_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_title",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_type_name",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "service_type_version",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      },
      {
        "name": "variable_names",
        "weight": 2,
        "value": [
          1,
          1
        ],
        "msgs": [],
        "children": []
      }
    ],
    "testname": "ioos_sos",
    "source_name": "http://thredds.aoos.org/thredds/sos/aoos/cruises/ecofoci/4mf01.nc?service=SOS&version=1.0.0&request=GetCapabilities"
  }
}
```

Here is my env:
```
> conda list                                                                                                                                                                                                       ⏎
# packages in environment at /home/filipe/miniconda3/envs/TEST:
#
asn1crypto                0.22.0                   py36_0    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cf_units                  1.1.3                    py36_1    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
compliance-checker        3.1.1                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
expat                     2.2.1                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        1    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.6                      py36_1    conda-forge
intel-openmp              2018.0.0             h15fc484_7    defaults
isodate                   0.6.0                      py_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            1    conda-forge
krb5                      1.14.2                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          4    conda-forge
libnetcdf                 4.4.1.1                       6    conda-forge
libssh2                   1.8.0                         1    conda-forge
libxml2                   2.9.5                         0    conda-forge
libxslt                   1.1.29                        5    conda-forge
lxml                      4.1.0                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
mkl                       2018.0.0             hb491cac_4    defaults
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.0                    py36_0    conda-forge
numpy                     1.13.3           py36ha12f23b_0    defaults
openssl                   1.0.2l                        0    conda-forge
owslib                    0.15.0                     py_0    conda-forge
pendulum                  1.3.0                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pygeoif                   0.7                      py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.3                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pytzdata                  2017.2.2                   py_0    conda-forge
readline                  6.2                           0    conda-forge
regex                     2017.07.28               py36_0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
tzlocal                   1.4                      py36_0    conda-forge
udunits2                  2.2.23                        1    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

**Comment by ocefpaf** [comment]
> but I had success by wrapping the URL in quotes

That may be it. I always do that automatically when copying-n-pasting URLs that I did not even notice this difference.

**Comment by mwengren** [comment]
Yes, wrapping URL in quotes works here as well.  

I've never done that in all the other tests I've run with CC, why the difference here?  Would be great to have consistency there... and ideally I'd favor it running without the necessity to wrap URL params in quotes, seems awkward.

**Comment by ocefpaf** [comment]
> I've never done that in all the other tests I've run with CC, why the difference here?

You probably had simpler URLs before without the `&`, for example.

> Would be great to have consistency there... and ideally I'd favor it running without the necessity to wrap URL params in quotes, seems awkward.

I don't know of any shell where that is possible. But I am only versed in bash, and zsh. Usually, the standard **is** to quote URLs.

**Comment by mwengren** [comment]
Yes, mostly I had only been testing OPeNDAP URLs, that probably explains the difference.  This runs up against the limit of my Python knowledge a bit, but I'm surprised you can't pass an unquoted URL string to argparse with an `&` and there be a way for it to handle and submit transparently via requests or urllib to the target.   

As long as it's documented correctly what's expected, no big deal though.  I see examples in the [README](https://github.com/ioos/compliance-checker/) though with unquoted URL parameters, we should update those or others may run into the same issues I have.

**Comment by ocefpaf** [comment]
>  This runs up against the limit of my Python knowledge a bit

It is not a Python limitation it is how the shell interpret the special characters. I don't think we can do anything and quoting is quite standard for CLI stuff that most people ends up doing it without even noticing.

With that said, if we do want more people using the CLI it would be nice to show example with the quotes.

**Comment by Bobfrat** [comment]
@mwengren the README has been updated with urls in quotes
