### ISSUE TITLE
Checker crashes on files non-string standard_name

### ISSUE THREAD

**Issue by drf5n** [ioos/compliance-checker#542]
I had a file with this bad bit of CDL in it and the compliance checker crashed on the mis-configured standard_name with the integer type:

```
        ...
	float hgrid_face_x(n_hgrid_face) ;
		hgrid_face_x:long_name = "x_coordinate of 2D mesh face" ;
		hgrid_face_x:standard_name = 0 ;
		hgrid_face_x:units = "m" ;
		hgrid_face_x:mesh = "hgrid" ;
        ...

```

```
$ compliance-checker -v -t cf test.nc
Running Compliance Checker on the dataset from: test.nc
Traceback (most recent call last):
  File "/Users/drf/anaconda/envs/python3/bin/compliance-checker", line 11, in <module>
    load_entry_point('compliance-checker==3.0.4', 'console_scripts', 'compliance-checker')()
  File "/Users/drf/anaconda/envs/python3/bin/cchecker.py", line 73, in main
    args.format)
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/runner.py", line 53, in run_checker
    *checker_names)
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/suite.py", line 139, in run
    checker.setup(ds)
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/cf/cf.py", line 107, in setup
    self._find_geophysical_vars(ds)
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/cf/cf.py", line 289, in _find_geophysical_vars
    self._geophysical_vars[ds] = cfutil.get_geophysical_variables(ds)
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/cfutil.py", line 274, in get_geophysical_variables
    if is_geophysical(ds, variable):
  File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/compliance_checker/cfutil.py", line 137, in is_geophysical
    if 'status_flag' in standard_name or hasattr(ncvar, 'flag_meanings'):
TypeError: argument of type 'numpy.int32' is not iterable
$
```
I realize the problem is within my file, (now fixed,) but perhaps the compliance checker should check types and report the error in the input rather than hard faulting.

Thanks

**Comment by benjwadams** [comment]
This is definitely one reason I am in favor of type-checking features in Python 3.

**Comment by kwilcox** [comment]
Real world examples: I've seen people represent units of dimensionless parameters (pH) as lots of interesting things (NaN, 1, "1", "pH"). I've also seen PPT and PPM represented as decimal numbers (0.001) and permil (‰). Should we warn when a unit is not a string?

**Comment by Bobfrat** [comment]
Yeah we'll need to check that units are a string

**Comment by benjwadams** [comment]
This is broadly a class of issues which apply to the data types when fetching the attributes from the netCDF files.  The standard used says the datatype should be one type or another, but it can be anything inside the netCDF file proper.   I'm considering overriding `__getattr__` for the netCDF4.Dataset through subclassing to check the type based upon the particular spec being used.

**Comment by kwilcox** [comment]
`compliance-checker` should just implement what the CF spec says regarding the `units` attribute. The values should all be strings and the checker should report errors if they are not.

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#units

You can already check the type of a retrieved attribute value... why do you need to subclass anything?

**Comment by benjwadams** [comment]
Closing out this issue in light of the recently merged commit.  Please reopen if there are any additional difficulties with non-string units/standard_name.
