### ISSUE TITLE
PyPI install broken due to NetCDF4 1.4.0 package

### ISSUE THREAD

**Issue by lwgordonimos** [ioos/compliance-checker#579]
Something has changed in "NetCDF==1.4.0" which causes a basic "out of the box" install of compliance-checker from PyPI to fail due to the "netcdftime" module. Since the package is not pinned with a maximum version, any new installs of "compliance-checker" will be broken by default.

Not sure which is the most appropriate solution for this package, but I've included two actions which resolve the issue for me.

## Steps to replicate:

```bash
$ virtualenv compliance-checker
$ source compliance-checker/bin/activate
$ pip install compliance-checker

$ pip freeze
certifi==2018.4.16
cf-units==1.2.0
cftime==1.0.0b1
chardet==3.0.4
compliance-checker==4.0.0
Cython==0.28.2
idna==2.6
isodate==0.6.0
Jinja2==2.10
lxml==4.2.1
MarkupSafe==1.0
netCDF4==1.4.0
numpy==1.14.3
OWSLib==0.16.0
pendulum==2.0.1
pygeoif==0.7
pyproj==1.9.5.1
python-dateutil==2.7.3
pytz==2018.4
pytzdata==2018.5
regex==2017.7.28
requests==2.18.4
six==1.11.0
tabulate==0.8.2
typing==3.6.4
urllib3==1.22

$ compliance-checker -l
Traceback (most recent call last):
  File "/home/lwgordon/virtualenvs/compliance-checker/bin/compliance-checker", line 7, in <module>
    from cchecker import main
  File "/home/lwgordon/virtualenvs/compliance-checker/bin/cchecker.py", line 7, in <module>
    from compliance_checker.cf.util import download_cf_standard_name_table
  File "/home/lwgordon/virtualenvs/compliance-checker/local/lib/python2.7/site-packages/compliance_checker/cf/__init__.py", line 1, in <module>
    from compliance_checker.cf.cf import (
  File "/home/lwgordon/virtualenvs/compliance-checker/local/lib/python2.7/site-packages/compliance_checker/cf/cf.py", line 8, in <module>
    from compliance_checker.cf import util
  File "/home/lwgordon/virtualenvs/compliance-checker/local/lib/python2.7/site-packages/compliance_checker/cf/util.py", line 10, in <module>
    from cf_units import Unit
  File "/home/lwgordon/virtualenvs/compliance-checker/local/lib/python2.7/site-packages/cf_units/__init__.py", line 41, in <module>
    import netcdftime
ImportError: No module named netcdftime
```
## Solution 1 - install netcdftime
```
$ pip install netcdftime
Collecting netcdftime
Requirement already satisfied: numpy in ./compliance-checker/lib/python2.7/site-packages (from netcdftime) (1.14.3)
Requirement already satisfied: cython in ./compliance-checker/lib/python2.7/site-packages (from netcdftime) (0.28.2)
Installing collected packages: netcdftime
Successfully installed netcdftime-1.0.0a2

$ compliance-checker -l
IOOS compliance checker available checker suites:
 - acdd:1.1
 - acdd:1.3
 - cf:1.6
 - ioos:0.1
 - ioos:1.1
 - ioos_sos:0.1
```

## Solution 2 - downgrade NetCDF4 package
```
$ pip install NetCDF4==1.3.1
Collecting NetCDF4==1.3.1
  Using cached https://files.pythonhosted.org/packages/87/64/72e2bdf2a9663f91367f7ea5afe4ea96f8c024004f6c1b46b0aebefaf192/netCDF4-1.3.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.7 in ./compliance-checker/lib/python2.7/site-packages (from NetCDF4==1.3.1) (1.14.3)
Installing collected packages: NetCDF4
  Found existing installation: netCDF4 1.4.0
    Uninstalling netCDF4-1.4.0:
      Successfully uninstalled netCDF4-1.4.0
Successfully installed NetCDF4-1.3.1

$ compliance-checker -l
IOOS compliance checker available checker suites:
 - acdd:1.1
 - acdd:1.3
 - cf:1.6
 - ioos:0.1
 - ioos:1.1
 - ioos_sos:0.1
```

**Comment by ocefpaf** [comment]
The new `netcdf4` uses `cftime` instead of the old bundled `netcdftime`. I'll send a PR finxing this in a moment...

**Comment by ocefpaf** [comment]
There was no testing since the latest release for the CI to fail.
See PR #581 for the current failures and #580 for a fix.

**Comment by Bobfrat** [comment]
@lwgordonimos we just released the bug fix. https://github.com/ioos/compliance-checker/releases/tag/4.0.1

**Comment by benjwadams** [comment]
I just downloaded the current version (4.0.1) from PyPI and was able to run against a file, so it looks like this is fixed.  I'm going to close this issue.

**Comment by ocefpaf** [comment]
@benjwadams the current fix only pinned to older `netcdf4`, see https://github.com/ioos/compliance-checker/pull/581, but now that `cf_units 2.0` was released we can do better. I'll send a PR in a moment.
