### ISSUE TITLE
TypeError when running acdd test

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/compliance-checker#67]
The checker works fine for CF and for IOOS, but runs into an issue with ACDD.

$ compliance-checker --test=acdd -v http://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/carocoops.sun2.buoy_2013_12_31_02.nc
Running Compliance Checker on the dataset from: http://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/carocoops.sun2.buoy_2013_12_31_02.nc
Traceback (most recent call last):
  File "/home/matt-ubuntu/anaconda/bin/compliance-checker", line 9, in <module>
    load_entry_point('compliance-checker==1.0.0', 'console_scripts', 'compliance-checker')()
  File "/home/matt-ubuntu/anaconda/bin/cchecker.py", line 21, in main
    args.criteria)
  File "/home/matt-ubuntu/anaconda/lib/python2.7/site-packages/compliance_checker/runner.py", line 41, in run_checker
    score_groups = cs.run(ds, *checker_names)
  File "/home/matt-ubuntu/anaconda/lib/python2.7/site-packages/compliance_checker/suite.py", line 98, in run
    groups = self.scores(vals)
  File "/home/matt-ubuntu/anaconda/lib/python2.7/site-packages/compliance_checker/suite.py", line 361, in scores
    grouped = self._group_raw(raw_scores)
  File "/home/matt-ubuntu/anaconda/lib/python2.7/site-packages/compliance_checker/suite.py", line 426, in _group_raw
    msgs = sum(map(lambda x: x.msgs, v), [])
TypeError: can only concatenate list (not "str") to list

**Comment by daf** [comment]
This was fixed in 65d021c7cede3b8f31ad080e74e7db1cb888ffde
