### ISSUE TITLE
Error while running 'ioos' test on ERDDAP dataset

### ISSUE THREAD

**Issue by mwengren** [ioos/compliance-checker#755]
When I run the following in 4.3.3rc1:

```
compliance-checker -t ioos -f html http://testing.erddap.axds.co/erddap/tabledap/org_cormp_sun2
```
I get this error:
```
Traceback (most recent call last):
  File "/home/mwengren/miniconda3/envs/cc-test/bin/compliance-checker", line 11, in <module>
    load_entry_point('compliance-checker==4.3.3rc1', 'console_scripts', 'compliance-checker')()
  File "/home/mwengren/miniconda3/envs/cc-test/bin/cchecker.py", line 195, in main
    return_value, errors = ComplianceChecker.run_checker(args.dataset_location,
  File "/home/mwengren/miniconda3/envs/cc-test/lib/python3.8/site-packages/compliance_checker/runner.py", line 67, in run_checker
    score_groups = cs.run(ds, skip_checks, *checker_names)
  File "/home/mwengren/miniconda3/envs/cc-test/lib/python3.8/site-packages/compliance_checker/suite.py", line 368, in run
    groups = self.scores(vals)
  File "/home/mwengren/miniconda3/envs/cc-test/lib/python3.8/site-packages/compliance_checker/suite.py", line 746, in scores
    grouped = self._group_raw(raw_scores)
  File "/home/mwengren/miniconda3/envs/cc-test/lib/python3.8/site-packages/compliance_checker/suite.py", line 820, in _group_raw
    msgs = sum([x.msgs for x in v], [])
TypeError: can only concatenate list (not "str") to list
```

It works as expected on some other ERDDAP datasets, not sure what the issue might be here.

**Comment by mwengren** [comment]
Update: I get this error running the `ioos` test on several datasets:

```
compliance-checker -t ioos -f html http://erddap.secoora.org/erddap/tabledap/edu_usf_marine_comps_1407d550
compliance-checker -t ioos -f html https://erddap.sensors.ioos.us/erddap/tabledap/ssbn7-sun2wave-sun2w-sunset-n
```
But not on the `acdd` test:
```
compliance-checker -t acdd -f html http://erddap.secoora.org/erddap/tabledap/edu_usf_marine_comps_1407d550
compliance-checker -t acdd -f html https://erddap.sensors.ioos.us/erddap/tabledap/ssbn7-sun2wave-sun2w-sunset-n
```
Something local within my environment or within the code?

**Comment by ocefpaf** [comment]
> Something local within my environment or within the code?

Those are working for me. I have:

```
compliance-checker -V
IOOS compliance checker version 4.3.2
````


```
> conda list
# packages in environment at /home/filipe/miniconda3/envs/CC:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
antlr-python-runtime      4.7.2                 py38_1001    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cf-units                  2.1.3            py38hc1659b7_0    conda-forge
cffi                      1.14.0           py38hd463f26_0    conda-forge
cftime                    1.0.4.2          py38hc1659b7_0    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
compliance-checker        4.3.2                    py38_0    conda-forge
cryptography              2.8              py38h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               15_openblas    conda-forge
libcblas                  3.8.0               15_openblas    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               15_openblas    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.8                h5ec1e0e_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
lxml                      4.5.0            py38h7ec2d77_0    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py38hd35fb8e_102    conda-forge
numpy                     1.18.1           py38h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.1                     py_0    conda-forge
pendulum                  2.1.0                    py38_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
proj                      6.3.1                hc80f0dc_1    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygeoif                   0.7                        py_1    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyproj                    2.5.0            py38he3cd046_1    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.2           h9d8adfe_4_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pytzdata                  2019.3                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
regex                     2020.2.20        py38h516909a_0    conda-forge
requests                  2.23.0                   py38_0    conda-forge
setuptools                46.0.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
````

**Comment by daltonkell** [comment]
I'm not getting those errors, but I seem to be encountering an ERDDAP problem when testing the latter datasets:

```
$ compliance-checker -t acdd http://erddap.secoora.org/erddap/tabledap/edu_usf_marine_comps_1407d550

syntax error, unexpected $end, expecting ';'
context: Error { code=404; message="Not Found: HTTP status code=404 java.io.FileNotFoundException: http://erddap.sensors.axds.co/erddap/tabledap/edu_usf$
marine_comps_1407d550.nccsv?s.latitude\n(Error {\n code=404;\n message=\"Not Found: Your query produced no matching results. (nRows = 0)\";\n})";}^
syntax error, unexpected $end, expecting ';'
context: Error { code=404; message="Not Found: HTTP status code=404 java.io.FileNotFoundException: http://erddap.sensors.axds.co/erddap/tabledap/edu_usf$
marine_comps_1407d550.nccsv?s.longitude\n(Error {\n code=404;\n message=\"Not Found: Your query produced no matching results. (nRows = 0)\";\n})";}^


--------------------------------------------------------------------------------
                         IOOS Compliance Checker Report                         
                                    acdd:1.3                                    
http://wiki.esipfed.org/index.php?title=Category:Attribute_Conventions_Dataset_Discovery
--------------------------------------------------------------------------------
                               Corrective Actions                               
edu_usf_marine_comps_1407d550 has 20 potential issues


                               Highly Recommended                               
--------------------------------------------------------------------------------
Global Attributes
* keywords not present

variable "s.air_pressure" missing the following attributes:
* coverage_content_type
...
```

and

```
$ compliance-checker -t acdd https://erddap.sensors.ioos.us/erddap/tabledap/ssbn7-sun2wave-sun2w-sunset-n

Running Compliance Checker on the datasets from: ['https://erddap.sensors.ioos.us/erddap/tabledap/ssbn7-sun2wave-sun2w-sunset-n']
syntax error, unexpected $end, expecting ';'
context: Error { code=404; message="Not Found: HTTP status code=404 java.io.FileNotFoundException: http://erddap.sensors.axds.co/erddap/tabledap/ssbn7-su
n2wave-sun2w-sunset-n.nccsv?s.latitude\n(Error {\n code=404;\n message=\"Not Found: Your query produced no matching results. (nRows = 0)\";\n})";}^
syntax error, unexpected $end, expecting ';'
context: Error { code=404; message="Not Found: HTTP status code=404 java.io.FileNotFoundException: http://erddap.sensors.axds.co/erddap/tabledap/ssbn7-su
n2wave-sun2w-sunset-n.nccsv?s.longitude\n(Error {\n code=404;\n message=\"Not Found: Your query produced no matching results. (nRows = 0)\";\n})";}^


--------------------------------------------------------------------------------
                         IOOS Compliance Checker Report                         
                                    acdd:1.3                                    
http://wiki.esipfed.org/index.php?title=Category:Attribute_Conventions_Dataset_Discovery
--------------------------------------------------------------------------------
                               Corrective Actions                               
ssbn7-sun2wave-sun2w-sunset-n has 9 potential issues


                               Highly Recommended                               
--------------------------------------------------------------------------------
Global Attributes
* keywords not present
...
```
The first two datasets were free of any errors. Has this been encountered before?

**Comment by mwengren** [comment]
Thanks for weighing in.  My environment is below.  @ocefpaf I'm using the CC 4.3.3rc1, so that's one difference.  

I see I have some non conda-forge stuff in there, not even sure where that would have come from.  I may just scrap this environment and recreate.   

Also getting weird behavior with the PacIOOS dataset: https://pae-paha.pacioos.hawaii.edu/erddap/info/AWS-HIMB/index.html.  May create another issue for that if the env re-create doesn't help.

```
# packages in environment at /home/mwengren/miniconda3/envs/cc-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
antlr-python-runtime      4.7.2                 py38_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      2.14                   openblas    conda-forge
bleach                    3.1.1                      py_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
catalog-query             0.1.0                     dev_0    <develop>
certifi                   2019.11.28               py38_0    conda-forge
cf-units                  2.1.3            py38hc1659b7_0    conda-forge
cffi                      1.13.2           py38h8022711_0    conda-forge
cftime                    1.0.4.2          py38hc1659b7_0    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
compliance-checker        4.3.3rc1                   py_0    conda-forge/label/compliance-checker_rc
cryptography              2.8              py38h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cython                    0.29.15                  pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py38_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib_metadata        1.5.0                    py38_0    conda-forge
ipykernel                 5.1.4            py38h5ca1d4c_0    conda-forge
ipython                   7.12.0           py38h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.16.0                   py38_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py38_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py38_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py38_0    conda-forge
jupyter_core              4.6.3                    py38_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py38_1000    conda-forge
jupyter_latex_envs        1.4.4                 py38_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py38_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.7                h5ec1e0e_7    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
lxml                      4.5.0            py38h7ec2d77_0    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
mistune                   0.8.4           py38h516909a_1000    conda-forge
nbconvert                 5.6.1                    py38_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py38hd35fb8e_102    conda-forge
notebook                  6.0.3                    py38_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.1           py38h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.1                     py_0    conda-forge
pandas                    1.0.1                    pypi_0    pypi
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pendulum                  2.0.5                    py38_0    conda-forge
pexpect                   4.8.0                    py38_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pip                       20.0.2                     py_2    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.19                       py_2    conda-forge
pygeoif                   0.7                      pypi_0    pypi
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyproj                    2.5.0            py38h8ff28aa_0    conda-forge
pyqt                      5.12.3           py38hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py38h516909a_0    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pytzdata                  2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h516909a_0    conda-forge
pyzmq                     18.1.1           py38h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
regex                     2020.2.20        py38h516909a_0    conda-forge
requests                  2.23.0                   py38_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.2.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.3                    py38_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py38h516909a_4    conda-forge
traitlets                 4.3.3                    py38_0    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
validators                0.14.2                     py_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py38_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by ocefpaf** [comment]
> Thanks for weighing in. My environment is below. @ocefpaf I'm using the CC 4.3.3rc1, so that's one difference.

Sorry. You actually mentioned that above. I can reproduce that with both the conda `rc` and a pip develop install of the rc tag on GH.

**Comment by ocefpaf** [comment]
@daltonkell your version indicates that this was fixed in latest master. I tested against it and everything worked. Maybe we should issue a rc2?

**Comment by daltonkell** [comment]
> @daltonkell your version indicates that this was fixed in latest master. I tested against it and everything worked. Maybe we should issue a rc2?

A new RC should probably be released if this is the case. @benjwadams can you verify?

**Comment by mwengren** [comment]
Ok, this is resolved in latest version of master, closing this issue.

**Comment by benjwadams** [comment]
@daltonkell, feel free to go ahead and make a new release candidates once the most exigent IOOS 1.2 related PRs are merged.
