### ISSUE TITLE
Checker fails downloading latest standard name table

### ISSUE THREAD

**Issue by dnowacki-usgs** [ioos/compliance-checker#996]
**Version of compliance checker running:**
IOOS compliance checker version 5.0.2

**Describe the checker this affects:**
CF

**Attach a minimal CDL or NetCDF file which is able to reproduce the issue**
N/A

**To Reproduce:**
Run `compliance-checker -d latest`

_Expected result:_ 
update standard name list

_Actual result:_ 
```
Traceback (most recent call last):
  File "/Users/dnowacki/miniconda3/bin/compliance-checker", line 10, in <module>
    sys.exit(main())
  File "/Users/dnowacki/miniconda3/bin/cchecker.py", line 269, in main
    download_cf_standard_name_table(args.download_standard_names)
  File "/Users/dnowacki/miniconda3/lib/python3.10/site-packages/compliance_checker/cf/util.py", line 434, in download_cf_standard_name_table
    tables_tree = lxml.html.parse("http://cfconventions.org/documents.html")
  File "/Users/dnowacki/miniconda3/lib/python3.10/site-packages/lxml/html/__init__.py", line 937, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file 'http://cfconventions.org/documents.html': failed to load HTTP resource
```

**Describe the issue below:**
documents.html does not exist anymore. The list of standard names has been moved to vocabularies.html. I will submit a PR fixing this issue momentarily.

**Comment by MathewBiddle** [comment]
xref, if relevant: 
* https://github.com/cf-convention/discuss/issues/195
